-- MySQL Script generated by MySQL Workbench
-- Tue May 20 12:36:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_sql_fitzonesportclub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sql_fitzonesportclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sql_fitzonesportclub` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_sql_fitzonesportclub` ;

-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`staff` (
  `StaffID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `ContactNumber` VARCHAR(15) NULL DEFAULT NULL,
  `club_role` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`members` (
  `MemberID` INT NOT NULL,
  `FirstName` VARCHAR(50) NULL DEFAULT NULL,
  `LastName` VARCHAR(50) NULL DEFAULT NULL,
  `Date_of_Birth` DATE NULL DEFAULT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `ContactNumber` VARCHAR(50) NULL DEFAULT NULL,
  `medical_condition` TEXT NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`MemberID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`facility` (
  `FacilityID` INT NOT NULL,
  `FacilityName` VARCHAR(50) NULL DEFAULT NULL,
  `FacilityType` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`FacilityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`classes` (
  `ClassID` INT NOT NULL,
  `Title` VARCHAR(50) NULL DEFAULT NULL,
  `Instructor` INT NULL DEFAULT NULL,
  `FacilityID` INT NULL DEFAULT NULL,
  `Schedule` VARCHAR(100) NULL DEFAULT NULL,
  `MaxParticipants` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ClassID`),
  INDEX `Instructor` (`Instructor` ASC) VISIBLE,
  INDEX `FacilityID` (`FacilityID` ASC) VISIBLE,
  CONSTRAINT `classes_ibfk_1`
    FOREIGN KEY (`Instructor`)
    REFERENCES `db_sql_fitzonesportclub`.`staff` (`StaffID`),
  CONSTRAINT `classes_ibfk_2`
    FOREIGN KEY (`FacilityID`)
    REFERENCES `db_sql_fitzonesportclub`.`facility` (`FacilityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`classbooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`classbooking` (
  `ClassBookingID` INT NOT NULL,
  `ClubMemberID` INT NULL DEFAULT NULL,
  `ClassID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ClassBookingID`),
  INDEX `ClubMemberID` (`ClubMemberID` ASC) VISIBLE,
  INDEX `ClassID` (`ClassID` ASC) VISIBLE,
  CONSTRAINT `classbooking_ibfk_1`
    FOREIGN KEY (`ClubMemberID`)
    REFERENCES `db_sql_fitzonesportclub`.`members` (`MemberID`),
  CONSTRAINT `classbooking_ibfk_2`
    FOREIGN KEY (`ClassID`)
    REFERENCES `db_sql_fitzonesportclub`.`classes` (`ClassID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`attendance` (
  `AttendanceID` INT NOT NULL,
  `ClubStaffID` INT NULL DEFAULT NULL,
  `ClassBookingID` INT NULL DEFAULT NULL,
  `AttendanceDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`AttendanceID`),
  INDEX `ClubStaffID` (`ClubStaffID` ASC) VISIBLE,
  INDEX `ClassBookingID` (`ClassBookingID` ASC) VISIBLE,
  CONSTRAINT `attendance_ibfk_1`
    FOREIGN KEY (`ClubStaffID`)
    REFERENCES `db_sql_fitzonesportclub`.`staff` (`StaffID`),
  CONSTRAINT `attendance_ibfk_2`
    FOREIGN KEY (`ClassBookingID`)
    REFERENCES `db_sql_fitzonesportclub`.`classbooking` (`ClassBookingID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_sql_fitzonesportclub`.`facilitybooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sql_fitzonesportclub`.`facilitybooking` (
  `FacilityBookingID` INT NOT NULL,
  `ClubMemberID` INT NULL DEFAULT NULL,
  `ClubStaffID` INT NULL DEFAULT NULL,
  `FacilityID` INT NULL DEFAULT NULL,
  `BookingDate` DATE NULL DEFAULT NULL,
  `Duration` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`FacilityBookingID`),
  INDEX `ClubMemberID` (`ClubMemberID` ASC) VISIBLE,
  INDEX `ClubStaffID` (`ClubStaffID` ASC) VISIBLE,
  INDEX `FacilityID` (`FacilityID` ASC) VISIBLE,
  CONSTRAINT `facilitybooking_ibfk_1`
    FOREIGN KEY (`ClubMemberID`)
    REFERENCES `db_sql_fitzonesportclub`.`members` (`MemberID`),
  CONSTRAINT `facilitybooking_ibfk_2`
    FOREIGN KEY (`ClubStaffID`)
    REFERENCES `db_sql_fitzonesportclub`.`staff` (`StaffID`),
  CONSTRAINT `facilitybooking_ibfk_3`
    FOREIGN KEY (`FacilityID`)
    REFERENCES `db_sql_fitzonesportclub`.`facility` (`FacilityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;